export const adminPageContracts = {
  overview: {
    path: '/overview',
    inertiaPage: 'Admin/Overview',
    controller: 'Admin\\OverviewController@index',
    filters: [],
  },
  users: {
    path: '/users',
    inertiaPage: 'Admin/Users/Index',
    controller: 'Admin\\UserController@index',
    resource: 'UserResource',
    filters: ['search', 'type', 'status', 'gov', 'page'],
    actions: ['warn', 'suspend', 'ban'],
  },
  equipment: {
    path: '/equipment',
    inertiaPage: 'Admin/Equipment/Index',
    controller: 'Admin\\EquipmentController@index',
    resource: 'EquipmentResource',
    filters: ['search', 'category', 'status', 'page'],
    actions: ['hide', 'update', 'delete'],
  },
  rentals: {
    path: '/rentals',
    inertiaPage: 'Admin/Rentals/Index',
    controller: 'Admin\\RentalController@index',
    resource: 'RentalResource',
    filters: ['search', 'status', 'start_date', 'end_date', 'page'],
  },
  disputes: {
    path: '/disputes',
    inertiaPage: 'Admin/Disputes/Index',
    controller: 'Admin\\DisputeController@index',
    resource: 'DisputeResource',
    filters: ['search', 'status', 'page'],
    actions: ['resolve'],
  },
  finance: {
    path: '/finance',
    inertiaPage: 'Admin/Finance/Index',
    controller: 'Admin\\FinanceController@index',
    resource: 'PaymentResource',
    filters: ['tab', 'search', 'status', 'date', 'page'],
    actions: ['pause', 'review', 'release'],
  },
  complaints: {
    path: '/complaints',
    inertiaPage: 'Admin/Complaints/Index',
    controller: 'Admin\\ComplaintController@index',
    resource: 'ComplaintResource',
    filters: ['tab', 'search', 'type', 'status', 'page'],
    actions: ['warn', 'suspend', 'ban', 'reject', 'authorities'],
  },
  analytics: {
    path: '/analytics',
    inertiaPage: 'Admin/Analytics/Index',
    controller: 'Admin\\AnalyticsController@index',
    filters: ['date_range'],
  },
  reviews: {
    path: '/reviews',
    inertiaPage: 'Admin/Reviews/Index',
    controller: 'Admin\\ReviewController@index',
    resource: 'ReviewResource',
    filters: ['search', 'type', 'rating', 'status', 'page'],
    actions: ['keep', 'hide', 'report'],
  },
  audit: {
    path: '/audit',
    inertiaPage: 'Admin/AuditLog/Index',
    controller: 'Admin\\AuditLogController@index',
    resource: 'AuditLogResource',
    filters: ['search', 'admin', 'event', 'start_date', 'end_date', 'page'],
  },
  settings: {
    path: '/settings',
    inertiaPage: 'Admin/Settings/Index',
    controller: 'Admin\\SettingsController@index',
    resource: 'AdminResource',
    filters: ['tab'],
    actions: ['invite_admin', 'update_role', 'end_session', 'update_security'],
  },
};

export const resourceFields = {
  UserResource: ['id', 'name', 'phone', 'email', 'typeKey', 'statusKey', 'govKey', 'rating', 'kyc', 'joined', 'avatar'],
  EquipmentResource: ['id', 'name', 'categoryKey', 'owner', 'price', 'statusKey', 'images', 'insurance', 'rentCount'],
  RentalResource: ['id', 'tenant', 'owner', 'eq', 'duration', 'total', 'statusKey', 'startDate', 'endDate', 'insurance', 'escrow'],
  ComplaintResource: ['id', 'reporter', 'typeKey', 'target', 'date', 'priorityKey', 'statusKey'],
  DisputeResource: ['id', 'tenant', 'owner', 'eq', 'amount', 'date', 'statusKey'],
  PaymentResource: ['id', 'tenant', 'equipment', 'rent', 'insurance', 'date', 'statusKey'],
  ReviewResource: ['id', 'rater', 'raterType', 'target', 'targetType', 'rating', 'text', 'date', 'status', 'opId'],
  AuditLogResource: ['id', 'time', 'admin', 'adminKey', 'role', 'eventKey', 'details', 'ip'],
};
